[package]
name = "stack_trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-demangle = "0.1.21"
xmas-elf = "0.8.0"
log = "0.4.14"
bit_field = "0.10.1"